### ISSUE TITLE
DOC: What are the dlls for?

### ISSUE THREAD

**Issue by MartinThoma** [medmsyk/wendigopy#1]
What are the DLLs in https://github.com/medmsyk/wendigopy/tree/master/wendigo/bin/x64 doing? Where do they come from?

**Comment by medmsyk** [comment]
Sorry, I'm late.

Those dlls are for input simulation of keyboard and mouse, and they come from [WendigoCs](https://github.com/medmsyk/wendigocs) which I made.
It's mentioned in README.md of this repository, so please check that if you' re interested in.

> WendigoPy uses [SendInput](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput) to simulate inputs (implemented as [WendigoCs](https://github.com/medmsyk/wendigocs)).

Thanks for your issue!

**Comment by MartinThoma** [comment]
Thanks for the answer
